### PR TITLE
setting up docker-compose_dev.yml

### PR DESCRIPTION
**Pull request by anto6715**
In order to use the new compose, a new **dev** tag must be created on dockerhub for the following docker:

- [x] bluecloud-register
- [x] bluecloud-webapp
- [x] bluecloud-webservice
- ~~[ ] bluecloud-mysql~~ (now official mysql docker is used)

### CODE REVIEW

**Comment by anto6715** [comment]
@gottomondo Please write here when the dev tag for webapp and webservice is ready

**Comment by gottomondo** [comment]
done

**Comment by mdrudi** [comment]
docker-compose_local.yml non dovrebbe installare i tag latest ?

**Comment by anto6715** [comment]
> docker-compose_local.yml non dovrebbe installare i tag latest ?

Errore mio, è stato incluso erroneamente nel commit, l'ho ripristinato

**Comment by mdrudi** [comment]
@anto6715 - maybe this should be "_dev" instead of "-dev"

https://github.com/CMCC-Foundation/bluecloud-config/blob/ddc7598dd36439cb8676dca8e2a8d1fba1d2edf4/docker-compose_dev.yml#L9

**Comment by anto6715** [comment]
> @anto6715 - maybe this should be "_dev" instead of "-dev"
> 
> https://github.com/CMCC-Foundation/bluecloud-config/blob/ddc7598dd36439cb8676dca8e2a8d1fba1d2edf4/docker-compose_dev.yml#L9

updated

**Pull request merged**
